/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/todolist/DialogTodo copy.vue')['default']
    DialogTodo: typeof import('./components/todolist/DialogTodo.vue')['default']
    DialogTodoDelete: typeof import('./components/todolist/DialogTodoDelete.vue')['default']
    ListTasks: typeof import('./components/todolist/ListTasks.vue')['default']
    PersonsList: typeof import('./components/PersonsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Success: typeof import('./components/alertMessages/Success.vue')['default']
    TodoList: typeof import('./components/todolist/TodoList.vue')['default']
  }
}
